name: Start package loops

on:
  workflow_dispatch:

jobs:
  start_aggregator:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .   # install your local hamplots package

      - name: Run aggregator
        run: |
          python -m hamplots.aggregator

      - name: Run plotter
        run: |
          python -m hamplots.plotter

